theme: jekyll-theme-architect

name: Design patterns by Lebanese Java User Group

author: Pascal Fares

author_email: pascal.fares@cofares.net

title:  Design patterns en Java

google_analytics: UA-24954673-1


plugins: 
  - jekyll-sitemap
